### ISSUE TITLE
zoom in and out function using mouse scroll wheel

### ISSUE THREAD

**Issue by loatus** [maximecb/noisecraft#24]
I am requesting that the ability to zoom in and out using the mouse wheel would greatly enhance the app making it easier to copy and paste / select and move... groups of nodes when creating larger schematics. Also  that the darker blue cables are changed to a lighter blue that may be more visible on the majority of computer monitors with their default display settings.. I make barely make out the blue cables with my display settings as it is

**Comment by maximecb** [comment]
Hello @loatus. I'm not sure how easy it would be to implement zooming in and out. If you have ideas let us know. In the meantime you can zoom out the entire browser window by pressing Ctrl + Minus.

I'm not sure what you mean about the darker blue cables because they are very visible on my monitor, but I'll see what I can do about making it brighter, maybe making the background a tiny bit darker too.

**Comment by loatus** [comment]
I didn't realise you could zoom in and out like that... yeah that works fine for me as is. Thanks very much for reply

**Comment by maximecb** [comment]
I made the blue connections a little brighter and the background a little darker for you.
