### ISSUE TITLE
Bug preventing from creating new nodes on Chrome

### ISSUE THREAD

**Issue by Artaud** [maximecb/noisecraft#32]
Hi! I'm really interested in trying Noisecraft, however I encountered a roadblock issue.
I cannot add new nodes on Chrome (using version 91.0.4472.114). On Firefox, I can add them with no problem.
When I try to add a node, this exception comes up:

Uncaught DOMException: 
Failed to execute 'releasePointerCapture' on 'Element': No active pointer with the given id is found. at Editor.onClick (http://localhost:7773/public/editor.js:119:28) onClick @ editor.js:119

**Comment by Artaud** [comment]
BTW I found about Noisecraft through your blog (which I do not follow and was delivered to me randomly through the Google discover feed)

**Comment by maximecb** [comment]
Hello Artaud. Can you provide some details on your configuration, such as: are you on macOS, Linux, or a Chromebook? Are you using a mouse or a touchpad, etc?

Additionally, if you have time to try and investigate locally, it could be very helpful. I haven't experienced this issue in Chrome on macOS and Linux so it would be hard for me to debug.

> BTW I found about Noisecraft through your blog (which I do not follow and was delivered to me randomly through the Google discover feed)

Neat! :)

**Comment by Artaud** [comment]
Sure, I've got it running locally and basically have a day off so I'll look into it :)

I'm on Ubuntu 20.04, having mouse, touchpad and a touch-enabled screen as mouse inputs so that might have something to do with it.

**Comment by maximecb** [comment]
Thank you Artaud :)

For reference, I've tested it on the touchpad on my MacBook Air, and with the mouse on my desktop, both of which work fine. However, with the touchscreen on my laptop, it works very poorly. I haven't really investigated why. I think it might be because it treats the screen surface as having multiple pointers (multiple fingers).

Maybe just ignoring secondary pointers would work 🤔  the JS pointer handling is pretty unintuitive I find.

**Comment by Artaud** [comment]
Ok, it was just an undefined pointerId here https://github.com/maximecb/noisecraft/blob/2ef05a2f07afb8ee631a9d0c32575be37dc90a2b/public/editor.js#L119. 
Apparently my version of Chrome throws a DOMException there while Firefox and others do not.

I am not too versed in doing pull requests so I mashed the fix up together with two other unrelated commits (for better development) into one PR. Are you okay with that or should I try to find a way to split them up?

**Comment by maximecb** [comment]
Surprised that the pointerId can even be undefined. How strange. Thank you for taking the time to investigate.

I would rather these things be separate because I'm trying to minimize dependencies, would rather not add a dependency to nodemon. Logging the address and port seems like a good idea though.

**Comment by Artaud** [comment]
Sure, I'll do what I can :)
Absolutely understand the dependency worry. This is just a dev dependency though and I find that at development and especially debugging with it is much more comfortable. Anyway, I'll split it up and you'll accept what you want.

Now, with that out of the way, let me do some rambling...

The software is amazing, I have to say. I was using Audiomulch back in the day and while I had tremendous fun with it, it's by far the friendliest music software I've been ever exposed to for experimental music. However it ran only on Windows and so when I started working in the software industry and switched everything around me to Linux, I had no simple way to use it anymore. I tried to get into PD and MAX/MSP but those were kinda too hardcore for me. Noisecraft seems to aim at the sweet spot between those and with it's enormous accessibility, I think it could be a very successful project.
Also nice to see someone actually using those ES6 classes :) lots of JS folks are hesitant to switch AFAIK. I came to JS from a Java background so it's only natural to me.

Can I be so rude as to offer a list of things that I think would be awesome in Noisecraft?

- audio IN. Have you thought about it? Are there any blockers? Would open enormous possibilities.
- some sort of formalized API for the Nodes. Would be great for external contributors that only want to add an effect or instrument.
- hovering over ports should make them show up a little border around so you know you're on the port before you click....it has happened to me several times already that I missclicked the port which is kinda annoying
- it seems a little weird that you can drag multiple cables from on an output, but cannot put multiple cables into an input. Now I know there's "Add" element (which was called Mixer in Audiomulch IIRC), which seems to me a little redundant. What if you allowed multiple inputs into a port, which would then act like the Add element is prepended before the port? That could in some cases help keep the dashboard clutter-free. Of course the Add element is justified in the case that you want to route higher number of outputs into a higher number of inputs, then the Add element itself could help keep cables count to a minimum. So that's something to think about.
If allowing multiple inputs, you would lose a way to delete cables - so I propose "selectable cables". But I'm not sure how simple that is given the current implementation.
- Add node should have configurable number of inputs
- since a single click on a Node does nothing (maybe a bug?), I think it doesn't make sense to have the config on a double click. So either the single click should "select" the node (so you can then e.g. delete it with a DEL key) or single click should bring up the config right away.
- when adding a node, you get a nice on-hover tooltip on each of them. This does not appear when the Node is actually placed on the board, but I think it would still be helpful.


I'm definitely eager to take on some of that. While I have a family to feed and play with and jobs to be done, this is something I would love to sit with from time to time and contribute.

**Comment by Artaud** [comment]
Oh and there's https://github.com/ramirezd42/vst-js just waiting to be encapsulated in a node :)

**Comment by maximecb** [comment]
Thanks for the fixes Artaud 👌  :)

> Also nice to see someone actually using those ES6 classes :) lots of JS folks are hesitant to switch AFAIK. I came to JS from a Java background so it's only natural to me.

I think the modules and classes make the code quite a bit more readable. The downside is that Firefox and Safari don't seem to support `import` within the audioworklet (audio thread) yet. May eventually need to use something like `esbuild`.

> Can I be so rude as to offer a list of things that I think would be awesome in Noisecraft?

Sure. I'm happy to see that you're excited about the project and I want to remain open minded. Don't take it personally if I'm being very conservative though. It's taken me about a year of part-time work to get to this point, and I feel like there's still many basic issues to be solved. There's a few minor UI bugs, but I may also need to refactor the way the editor works to avoid recreating nodes as that's slower for larger projects and can introduce subtle bugs. Generally speaking, I'd prefer to grow this software gradually and improve the testing situation.

> hovering over ports should make them show up a little border around so you know you're on the port before you click....it has happened to me several times already that I misclicked the port which is kinda annoying

That sounds good. I will try out the PR you opened for this 👌 

> when adding a node, you get a nice on-hover tooltip on each of them. This does not appear when the Node is actually placed on the board, but I think it would still be helpful.

There's a tooltip showing the node type, but we could have it show `NodeType: node description text`. I would merge that as well.

> since a single click on a Node does nothing (maybe a bug?), I think it doesn't make sense to have the config on a double click. So either the single click should "select" the node (so you can then e.g. delete it with a DEL key) or single click should bring up the config right away.

Right now single-click allows you to drag the node, or in the case of knobs, to change the value.

> What if you allowed multiple inputs into a port, which would then act like the Add element is prepended before the port? That could in some cases help keep the dashboard clutter-free. Of course the Add element is justified in the case that you want to route higher number of outputs into a higher number of inputs, then the Add element itself could help keep cables count to a minimum. So that's something to think about.

Like you said, I think the problem then is that you need to be able to select the cables to delete them. It also means that add is given special treatment relative to other operators like multiplication. Not entirely opposed but it would mean redesigning the schema of projects, changes in the compiler. Also, just thinking about it... If you wanted to add 0.37 to something, then you'd have some input, and the constant 0.37 going into an input. I think that goes in the direction of making the software a bit more cryptic and harder to use for beginners.

> Add node should have configurable number of inputs

This I think I agree with. Some nodes will inevitably need a configurable number of inputs or outputs. That brings up the question of how to express that in the node schema and how to configure this in the node parameters menu, how to automatically assign a name to each input, but it seems doable.

> audio IN. Have you thought about it? Are there any blockers? Would open enormous possibilities.

Right now I don't really use the web audio API for processing audio data 😅  I generate my own code to produce audio samples. That might seem stupid, but I just don't trust the web audio API to behave the same on every browser, because the API surface is so huge, and there have been issues in this area in the past. To have an audio input, we'd need separate audio input nodes, we'd also have to ask for permission before getting audio input. Then, there's the problem that NoiseCraft doesn't really have any fourier-type effects because those are complex to implement and CPU-hungry. You could gate microphone audio, record it, add reverb, etc, but would it really be that interesting to play with? 🤔  Not completely opposed, but the implications in terms of added complexity are nontrivial IMO.

> some sort of formalized API for the Nodes. Would be great for external contributors that only want to add an effect or instrument.

I don't know what that would look like. I might be open, but the general idea with NoiseCraft is that you can design your own instruments and understand how they work. Eventually, you'll be able to group nodes together to create your own "modules", and then copy and paste modules into new tabs. I don't think I'd really want to merge a ready-made synth. I'd rather people create synths using primitives, group them into a custom module, and then if other users want to understand how said synth work, they can ungroup the nodes and look under the hood.

**Comment by maximecb** [comment]
Artaud fixed this bug 👌

**Comment by maximecb** [comment]
I added the node description to the node tooltip like you suggested. :)

**Comment by Artaud** [comment]
Nice, thank you!

út 7. 12. 2021 v 21:07 odesílatel Maxime Chevalier-Boisvert <
***@***.***> napsal:
