### ISSUE TITLE
Server side API method refactoring proposal.

### ISSUE THREAD

**Issue by victorKochkarev** [maximecb/noisecraft#41]
Hello,

I reviewed the server-side of the project and noticed a few things about how it can be made better.

At the moment, the server has the following supported API endpoints:

```
GET /public
GET /
GET /:projectId([0-9+])
GET /help
GET /browse
GET /allthestats
POST /register
POST /login
POST /share
GET /browse/:from
GET /get_project/:id
GET /del_project/:id - commented out
```

I would recommend restructuring project entity-related URLs to match standard REST methods.

GET /get_project/:id -> GET /projects/{project_id} - get project by id

GET /browse/:from -> GET /projects
with the following optional query params - limit, offset. Potentially this method can be used to browse other users projects, but it can be decided in future.

POST /share -> POST /projects.  This endpoint can be used just to save the project object. 

GET /del_project/:id -> DELETE /projects/{id} - standard method to delete a resourse. 

I would be happy to work on these changes.

**Comment by maximecb** [comment]
Hi Victor,

Glad to see you're interested in the project :)

I like some of your suggestions but others I'm not sure 🤔 

> GET /get_project/:id -> GET /projects/{project_id} - get project by id

I'm not sure what you mean with the {project_id} notation. You mean providing this as JSON? If so, why?

> GET /browse/:from -> GET /projects

with the following optional query params - limit, offset. Potentially this method can be used to browse other users projects, but it can be decided in future.

I can see this route being renamed `list` instead of `browse` as I think it would be more descriptive. I think the :from parameter is what you call the offset? Adding a limit parameter makes sense.

> POST /share -> POST /projects. This endpoint can be used just to save the project object.

When you say can be used just to save, you mean to update the shared project?

I don't love the idea of having multiple routes with the same name because it seems to me that could maks it a bit more awkward to discuss them.?

> GET /del_project/:id -> DELETE /projects/{id} - standard method to delete a resource.

I'm ok with using the delete method, that makes sense, though again a little skeptical about using the same route name. Is that standard in web API design?

**Comment by victorKochkarev** [comment]
HI Maxime,

I like the project and would like to support it mainly from the back-end side. Even its core and beauty lay within the front end part.

Let me try to explain the point.

```
 GET /get_project/:id -> GET /projects/{project_id} - get project by id
```

in this case {project_id} is the same as :id in your case - sorry for the confusion. 
But because HTTP GET method is used, there is not need to use get_ prefix within the url name. project_id would remain as an integer, and the response would be the same JSON object.
Also I have proposed plural form of the word project - this is more a conventional was of calling it. 


> I don't love the idea of having multiple routes with the same name because it seems to me that could maks it a bit more awkward to discuss them.?

I understand your point, it feels a little bit odd in the begging. But this is considered to be the standard approach.

let me better send a few articles on this topic, otherwise I would write the same information.

https://medium.com/@mwaysolutions/10-best-practices-for-better-restful-api-cbe81b06f291
https://www.freecodecamp.org/news/rest-api-best-practices-rest-endpoint-design-examples/
https://docs.microsoft.com/en-us/azure/architecture/best-practices/api-design

In a way it is more like RPC vs REST approach.

> POST /share -> POST /projects. This endpoint can be used just to save the project object.

> When you say can be used just to save, you mean to update the shared project?

At the moment the only case when user persists the project to the database, is only when user wants to share the project.
At later stages it might be willing to save it just in order to save it, and work on the project at the later moment.

For updating saved project it would be better to use /projects/:id PATCH or PUT method. But it can be implemented at later stage.

If needed I can implement an illustrative API prototype - it might show a few benefits.

**Comment by maximecb** [comment]
Thanks for taking the time to explain Victor.

I've renamed the `/browse` endpoint to `/list` because I felt that was more descriptive. IMO it should remain separate from projects because it doesn't do the same thing, it returns a different kind of data (a list of entries with titles as opposed to project data. However, I like your other proposals.

> with the following optional query params - limit, offset. Potentially this method can be used to browse other users projects, but it can be decided in future.

Let's add limit and offset parameters to the `/list` endpoint 👍 

> GET /get_project/:id -> GET /projects/{project_id} - get project by id

Sounds good 👍 

> POST /share -> POST /projects. This endpoint can be used just to save the project object.

Sounds good 👍 

> GET /del_project/:id -> DELETE /projects/{id} - standard method to delete a resource.

Sounds good, but, I think we'll want to leave that commented for now. What's also missing from the server side is that we need to have special admin and moderator users. We'd want to add a `status` or `access` field to the `users` table, and check that only moderator or above users can delete projects.

> I would be happy to work on these changes.

Okay :)

**Comment by maximecb** [comment]
I'd like to have a separate showcase in the `/browse` page as was done here: https://z.musictools.live/ (see browse page)

For the Zupiter app, I hand-edited the HTML directly, but this is a hack. Ideally, there would be some way for admin users to edit an ordered list of projects to display in the showcase. This could be supplied as a simple list of project ids, eg [502, 86, 1, 15, 102].

This means we might want separate API endpoints for getting and setting the showcase, e.g.

```
# Returns data in the same format as the /list endpoint
GET /showcase?limit=N
```

I think we might want a separate endpoint from `/list` because the showcase is very much its own list, with a different order from what would be returned by `/list`.

```
# Takes a JSON ordered list of project ids, requires verification that user is admin
POST /showcase
```

@victorKochkarev what do you think?

**Comment by victorKochkarev** [comment]
Hi Maxime,
Too many things are discussed within the same issue, but this is great!

Let's keep list/browse methods the way they are for now. But I can add optional limit and offset params - but its functionality will not be changed the way it is right now.

Later project list endpoint could return data based on potential future factors like belonging to a user, being featured, public, or having the most likes, comments, or whatever will be needed.

For now I will make the following changes:

> GET /get_project/:id -> GET /projects/{project_id} - get project by id
> POST /share -> POST /projects. This endpoint can be used just to save the project object.

**Comment by maximecb** [comment]
Sounds good 👍

**Comment by victorKochkarev** [comment]
Probably discussions might be a better place for this kind of items.

**Comment by maximecb** [comment]
I created a discussion for the featured section and admin access here: https://github.com/maximecb/noisecraft/discussions/49
