### ISSUE TITLE
message : 'failed to share project'

### ISSUE THREAD

**Issue by loatus** [maximecb/noisecraft#91]
I am not able to share projects currently... message : 'failed to share project'  :(

**Comment by maximecb** [comment]
Hey Daniel. I'd like to help track down the problem because if people can't share projects, that's really unfortunate. Someone was able to share a projects 11 hours ago, and I just did as well to make sure there was nothing obviously wrong.

Could you please save the project you are trying to share into a file and upload it somewhere? That way I can take a look at it on my end.

Could you also share some info about which browser you are using and whether you are on Mac/Linux/Windows?

**Comment by maximecb** [comment]
Let me know if the problem still occurs, and if so, please try to send me the offending project file :)

**Comment by loatus** [comment]
Hi, I have been away from my computer for a while, otherwise I would have got back to you sooner.

I haven't been able to share any noisecraft files  while using the Opera browser since I last mentioned the issue. I have been using Opera browser as for me when I try using Chrome the cables appear invisible. I am able to share on Chrome though having just done a test . Maybe there is a fix you know of that will remedy the Chrome cable invisibility issue.  
![image](https://user-images.githubusercontent.com/30633486/171670622-0b607064-395f-49f9-98b9-4db4d9b472f0.png)
